services:
  nginx:
    image: nginx:alpine
    container_name: camagru_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - camagru_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: camagru_php
    user: "${UID}:${GID}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      APP_URL: ${APP_URL}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - camagru_network

  db:
    image: mariadb:11
    container_name: camagru_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - camagru_network

volumes:
  db_data:

networks:
  camagru_network: